name: Build dev firmware

on:
  push:
    branches:
      - 'main'
      - 'dev/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: submodules
      run: git submodule update --init --recursive

    - name: Setup env
      run: |
        echo "OCT4_BUILD_TAG=CI" >> $GITHUB_ENV
        echo "OCT4_ARTIFACT_TAG=${GITHUB_REF##*/}-$(scripts/build_tag.sh)" >> $GITHUB_ENV

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'

    - run: |
        pip3 install --upgrade pip
        pip3 install -r .github/workflows/requirements.txt

    - name: Compile firmware
      working-directory: .
      run: |
        pio run -e dev
        pio run -e prod

    - name: Copy artifact
      uses: actions/upload-artifact@v3
      with:
        name: oct4-${{env.OCT4_ARTIFACT_TAG}}
        path: .pio/build/*/*.hex
